trigger:
  branches:
    include:
    - main

pool:
  vmImage: windows-latest
  
variables:
  - name: consoleAppFolder
    value: 'backend\ConsoleApp1'

  - name: consoleAppProject
    value: 'ConsoleApp1/ConsoleApp1/ConsoleApp1.csproj'

steps:
- checkout: self
  persistCredentials: true


- script: echo Executando pipeline

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: $(consoleAppProject)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    publishWebProjects: false
    projects: $(consoleAppProject)
    arguments: '--runtime win-x64'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: false
    zipAfterPublish: false
    projects: $(consoleAppProject)
    arguments: '--configuration release --output $(Build.ArtifactStagingDirectory)/backend'

- powershell: |
   dir '$(Build.ArtifactStagingDirectory)\$(consoleAppFolder)'
  displayName: 'PowerShell Script'

- powershell: |
   cd "$(Build.ArtifactStagingDirectory)\$(consoleAppFolder)"
   
   dotnet .\ConsoleApp1.dll
  displayName: 'PowerShell Script'
